# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/murkeert/workplace/KPL/amazon-kinesis-producer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/murkeert/workplace/KPL/amazon-kinesis-producer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/murkeert/workplace/KPL/amazon-kinesis-producer/CMakeFiles /Users/murkeert/workplace/KPL/amazon-kinesis-producer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/murkeert/workplace/KPL/amazon-kinesis-producer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named test_driver

# Build rule for target.
test_driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_driver
.PHONY : test_driver

# fast build rule for target.
test_driver/fast:
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/build
.PHONY : test_driver/fast

#=============================================================================
# Target rules for targets named kinesis_producer

# Build rule for target.
kinesis_producer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kinesis_producer
.PHONY : kinesis_producer

# fast build rule for target.
kinesis_producer/fast:
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/build
.PHONY : kinesis_producer/fast

aws/auth/mutable_static_creds_provider.o: aws/auth/mutable_static_creds_provider.cc.o

.PHONY : aws/auth/mutable_static_creds_provider.o

# target to build an object file
aws/auth/mutable_static_creds_provider.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/auth/mutable_static_creds_provider.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/auth/mutable_static_creds_provider.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/auth/mutable_static_creds_provider.cc.o
.PHONY : aws/auth/mutable_static_creds_provider.cc.o

aws/auth/mutable_static_creds_provider.i: aws/auth/mutable_static_creds_provider.cc.i

.PHONY : aws/auth/mutable_static_creds_provider.i

# target to preprocess a source file
aws/auth/mutable_static_creds_provider.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/auth/mutable_static_creds_provider.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/auth/mutable_static_creds_provider.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/auth/mutable_static_creds_provider.cc.i
.PHONY : aws/auth/mutable_static_creds_provider.cc.i

aws/auth/mutable_static_creds_provider.s: aws/auth/mutable_static_creds_provider.cc.s

.PHONY : aws/auth/mutable_static_creds_provider.s

# target to generate assembly for a file
aws/auth/mutable_static_creds_provider.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/auth/mutable_static_creds_provider.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/auth/mutable_static_creds_provider.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/auth/mutable_static_creds_provider.cc.s
.PHONY : aws/auth/mutable_static_creds_provider.cc.s

aws/auth/test/mutable_static_creds_provider_test.o: aws/auth/test/mutable_static_creds_provider_test.cc.o

.PHONY : aws/auth/test/mutable_static_creds_provider_test.o

# target to build an object file
aws/auth/test/mutable_static_creds_provider_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/auth/test/mutable_static_creds_provider_test.cc.o
.PHONY : aws/auth/test/mutable_static_creds_provider_test.cc.o

aws/auth/test/mutable_static_creds_provider_test.i: aws/auth/test/mutable_static_creds_provider_test.cc.i

.PHONY : aws/auth/test/mutable_static_creds_provider_test.i

# target to preprocess a source file
aws/auth/test/mutable_static_creds_provider_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/auth/test/mutable_static_creds_provider_test.cc.i
.PHONY : aws/auth/test/mutable_static_creds_provider_test.cc.i

aws/auth/test/mutable_static_creds_provider_test.s: aws/auth/test/mutable_static_creds_provider_test.cc.s

.PHONY : aws/auth/test/mutable_static_creds_provider_test.s

# target to generate assembly for a file
aws/auth/test/mutable_static_creds_provider_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/auth/test/mutable_static_creds_provider_test.cc.s
.PHONY : aws/auth/test/mutable_static_creds_provider_test.cc.s

aws/kinesis/core/ipc_manager.o: aws/kinesis/core/ipc_manager.cc.o

.PHONY : aws/kinesis/core/ipc_manager.o

# target to build an object file
aws/kinesis/core/ipc_manager.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/ipc_manager.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/ipc_manager.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/ipc_manager.cc.o
.PHONY : aws/kinesis/core/ipc_manager.cc.o

aws/kinesis/core/ipc_manager.i: aws/kinesis/core/ipc_manager.cc.i

.PHONY : aws/kinesis/core/ipc_manager.i

# target to preprocess a source file
aws/kinesis/core/ipc_manager.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/ipc_manager.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/ipc_manager.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/ipc_manager.cc.i
.PHONY : aws/kinesis/core/ipc_manager.cc.i

aws/kinesis/core/ipc_manager.s: aws/kinesis/core/ipc_manager.cc.s

.PHONY : aws/kinesis/core/ipc_manager.s

# target to generate assembly for a file
aws/kinesis/core/ipc_manager.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/ipc_manager.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/ipc_manager.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/ipc_manager.cc.s
.PHONY : aws/kinesis/core/ipc_manager.cc.s

aws/kinesis/core/kinesis_producer.o: aws/kinesis/core/kinesis_producer.cc.o

.PHONY : aws/kinesis/core/kinesis_producer.o

# target to build an object file
aws/kinesis/core/kinesis_producer.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/kinesis_producer.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/kinesis_producer.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/kinesis_producer.cc.o
.PHONY : aws/kinesis/core/kinesis_producer.cc.o

aws/kinesis/core/kinesis_producer.i: aws/kinesis/core/kinesis_producer.cc.i

.PHONY : aws/kinesis/core/kinesis_producer.i

# target to preprocess a source file
aws/kinesis/core/kinesis_producer.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/kinesis_producer.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/kinesis_producer.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/kinesis_producer.cc.i
.PHONY : aws/kinesis/core/kinesis_producer.cc.i

aws/kinesis/core/kinesis_producer.s: aws/kinesis/core/kinesis_producer.cc.s

.PHONY : aws/kinesis/core/kinesis_producer.s

# target to generate assembly for a file
aws/kinesis/core/kinesis_producer.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/kinesis_producer.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/kinesis_producer.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/kinesis_producer.cc.s
.PHONY : aws/kinesis/core/kinesis_producer.cc.s

aws/kinesis/core/kinesis_record.o: aws/kinesis/core/kinesis_record.cc.o

.PHONY : aws/kinesis/core/kinesis_record.o

# target to build an object file
aws/kinesis/core/kinesis_record.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/kinesis_record.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/kinesis_record.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/kinesis_record.cc.o
.PHONY : aws/kinesis/core/kinesis_record.cc.o

aws/kinesis/core/kinesis_record.i: aws/kinesis/core/kinesis_record.cc.i

.PHONY : aws/kinesis/core/kinesis_record.i

# target to preprocess a source file
aws/kinesis/core/kinesis_record.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/kinesis_record.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/kinesis_record.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/kinesis_record.cc.i
.PHONY : aws/kinesis/core/kinesis_record.cc.i

aws/kinesis/core/kinesis_record.s: aws/kinesis/core/kinesis_record.cc.s

.PHONY : aws/kinesis/core/kinesis_record.s

# target to generate assembly for a file
aws/kinesis/core/kinesis_record.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/kinesis_record.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/kinesis_record.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/kinesis_record.cc.s
.PHONY : aws/kinesis/core/kinesis_record.cc.s

aws/kinesis/core/retrier.o: aws/kinesis/core/retrier.cc.o

.PHONY : aws/kinesis/core/retrier.o

# target to build an object file
aws/kinesis/core/retrier.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/retrier.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/retrier.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/retrier.cc.o
.PHONY : aws/kinesis/core/retrier.cc.o

aws/kinesis/core/retrier.i: aws/kinesis/core/retrier.cc.i

.PHONY : aws/kinesis/core/retrier.i

# target to preprocess a source file
aws/kinesis/core/retrier.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/retrier.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/retrier.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/retrier.cc.i
.PHONY : aws/kinesis/core/retrier.cc.i

aws/kinesis/core/retrier.s: aws/kinesis/core/retrier.cc.s

.PHONY : aws/kinesis/core/retrier.s

# target to generate assembly for a file
aws/kinesis/core/retrier.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/retrier.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/retrier.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/retrier.cc.s
.PHONY : aws/kinesis/core/retrier.cc.s

aws/kinesis/core/shard_map.o: aws/kinesis/core/shard_map.cc.o

.PHONY : aws/kinesis/core/shard_map.o

# target to build an object file
aws/kinesis/core/shard_map.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/shard_map.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/shard_map.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/shard_map.cc.o
.PHONY : aws/kinesis/core/shard_map.cc.o

aws/kinesis/core/shard_map.i: aws/kinesis/core/shard_map.cc.i

.PHONY : aws/kinesis/core/shard_map.i

# target to preprocess a source file
aws/kinesis/core/shard_map.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/shard_map.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/shard_map.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/shard_map.cc.i
.PHONY : aws/kinesis/core/shard_map.cc.i

aws/kinesis/core/shard_map.s: aws/kinesis/core/shard_map.cc.s

.PHONY : aws/kinesis/core/shard_map.s

# target to generate assembly for a file
aws/kinesis/core/shard_map.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/shard_map.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/shard_map.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/shard_map.cc.s
.PHONY : aws/kinesis/core/shard_map.cc.s

aws/kinesis/core/test/aggregator_test.o: aws/kinesis/core/test/aggregator_test.cc.o

.PHONY : aws/kinesis/core/test/aggregator_test.o

# target to build an object file
aws/kinesis/core/test/aggregator_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/aggregator_test.cc.o
.PHONY : aws/kinesis/core/test/aggregator_test.cc.o

aws/kinesis/core/test/aggregator_test.i: aws/kinesis/core/test/aggregator_test.cc.i

.PHONY : aws/kinesis/core/test/aggregator_test.i

# target to preprocess a source file
aws/kinesis/core/test/aggregator_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/aggregator_test.cc.i
.PHONY : aws/kinesis/core/test/aggregator_test.cc.i

aws/kinesis/core/test/aggregator_test.s: aws/kinesis/core/test/aggregator_test.cc.s

.PHONY : aws/kinesis/core/test/aggregator_test.s

# target to generate assembly for a file
aws/kinesis/core/test/aggregator_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/aggregator_test.cc.s
.PHONY : aws/kinesis/core/test/aggregator_test.cc.s

aws/kinesis/core/test/ipc_manager_test.o: aws/kinesis/core/test/ipc_manager_test.cc.o

.PHONY : aws/kinesis/core/test/ipc_manager_test.o

# target to build an object file
aws/kinesis/core/test/ipc_manager_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/ipc_manager_test.cc.o
.PHONY : aws/kinesis/core/test/ipc_manager_test.cc.o

aws/kinesis/core/test/ipc_manager_test.i: aws/kinesis/core/test/ipc_manager_test.cc.i

.PHONY : aws/kinesis/core/test/ipc_manager_test.i

# target to preprocess a source file
aws/kinesis/core/test/ipc_manager_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/ipc_manager_test.cc.i
.PHONY : aws/kinesis/core/test/ipc_manager_test.cc.i

aws/kinesis/core/test/ipc_manager_test.s: aws/kinesis/core/test/ipc_manager_test.cc.s

.PHONY : aws/kinesis/core/test/ipc_manager_test.s

# target to generate assembly for a file
aws/kinesis/core/test/ipc_manager_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/ipc_manager_test.cc.s
.PHONY : aws/kinesis/core/test/ipc_manager_test.cc.s

aws/kinesis/core/test/kinesis_record_test.o: aws/kinesis/core/test/kinesis_record_test.cc.o

.PHONY : aws/kinesis/core/test/kinesis_record_test.o

# target to build an object file
aws/kinesis/core/test/kinesis_record_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/kinesis_record_test.cc.o
.PHONY : aws/kinesis/core/test/kinesis_record_test.cc.o

aws/kinesis/core/test/kinesis_record_test.i: aws/kinesis/core/test/kinesis_record_test.cc.i

.PHONY : aws/kinesis/core/test/kinesis_record_test.i

# target to preprocess a source file
aws/kinesis/core/test/kinesis_record_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/kinesis_record_test.cc.i
.PHONY : aws/kinesis/core/test/kinesis_record_test.cc.i

aws/kinesis/core/test/kinesis_record_test.s: aws/kinesis/core/test/kinesis_record_test.cc.s

.PHONY : aws/kinesis/core/test/kinesis_record_test.s

# target to generate assembly for a file
aws/kinesis/core/test/kinesis_record_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/kinesis_record_test.cc.s
.PHONY : aws/kinesis/core/test/kinesis_record_test.cc.s

aws/kinesis/core/test/limiter_test.o: aws/kinesis/core/test/limiter_test.cc.o

.PHONY : aws/kinesis/core/test/limiter_test.o

# target to build an object file
aws/kinesis/core/test/limiter_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/limiter_test.cc.o
.PHONY : aws/kinesis/core/test/limiter_test.cc.o

aws/kinesis/core/test/limiter_test.i: aws/kinesis/core/test/limiter_test.cc.i

.PHONY : aws/kinesis/core/test/limiter_test.i

# target to preprocess a source file
aws/kinesis/core/test/limiter_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/limiter_test.cc.i
.PHONY : aws/kinesis/core/test/limiter_test.cc.i

aws/kinesis/core/test/limiter_test.s: aws/kinesis/core/test/limiter_test.cc.s

.PHONY : aws/kinesis/core/test/limiter_test.s

# target to generate assembly for a file
aws/kinesis/core/test/limiter_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/limiter_test.cc.s
.PHONY : aws/kinesis/core/test/limiter_test.cc.s

aws/kinesis/core/test/put_records_request_test.o: aws/kinesis/core/test/put_records_request_test.cc.o

.PHONY : aws/kinesis/core/test/put_records_request_test.o

# target to build an object file
aws/kinesis/core/test/put_records_request_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/put_records_request_test.cc.o
.PHONY : aws/kinesis/core/test/put_records_request_test.cc.o

aws/kinesis/core/test/put_records_request_test.i: aws/kinesis/core/test/put_records_request_test.cc.i

.PHONY : aws/kinesis/core/test/put_records_request_test.i

# target to preprocess a source file
aws/kinesis/core/test/put_records_request_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/put_records_request_test.cc.i
.PHONY : aws/kinesis/core/test/put_records_request_test.cc.i

aws/kinesis/core/test/put_records_request_test.s: aws/kinesis/core/test/put_records_request_test.cc.s

.PHONY : aws/kinesis/core/test/put_records_request_test.s

# target to generate assembly for a file
aws/kinesis/core/test/put_records_request_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/put_records_request_test.cc.s
.PHONY : aws/kinesis/core/test/put_records_request_test.cc.s

aws/kinesis/core/test/reducer_test.o: aws/kinesis/core/test/reducer_test.cc.o

.PHONY : aws/kinesis/core/test/reducer_test.o

# target to build an object file
aws/kinesis/core/test/reducer_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/reducer_test.cc.o
.PHONY : aws/kinesis/core/test/reducer_test.cc.o

aws/kinesis/core/test/reducer_test.i: aws/kinesis/core/test/reducer_test.cc.i

.PHONY : aws/kinesis/core/test/reducer_test.i

# target to preprocess a source file
aws/kinesis/core/test/reducer_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/reducer_test.cc.i
.PHONY : aws/kinesis/core/test/reducer_test.cc.i

aws/kinesis/core/test/reducer_test.s: aws/kinesis/core/test/reducer_test.cc.s

.PHONY : aws/kinesis/core/test/reducer_test.s

# target to generate assembly for a file
aws/kinesis/core/test/reducer_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/reducer_test.cc.s
.PHONY : aws/kinesis/core/test/reducer_test.cc.s

aws/kinesis/core/test/retrier_test.o: aws/kinesis/core/test/retrier_test.cc.o

.PHONY : aws/kinesis/core/test/retrier_test.o

# target to build an object file
aws/kinesis/core/test/retrier_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/retrier_test.cc.o
.PHONY : aws/kinesis/core/test/retrier_test.cc.o

aws/kinesis/core/test/retrier_test.i: aws/kinesis/core/test/retrier_test.cc.i

.PHONY : aws/kinesis/core/test/retrier_test.i

# target to preprocess a source file
aws/kinesis/core/test/retrier_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/retrier_test.cc.i
.PHONY : aws/kinesis/core/test/retrier_test.cc.i

aws/kinesis/core/test/retrier_test.s: aws/kinesis/core/test/retrier_test.cc.s

.PHONY : aws/kinesis/core/test/retrier_test.s

# target to generate assembly for a file
aws/kinesis/core/test/retrier_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/retrier_test.cc.s
.PHONY : aws/kinesis/core/test/retrier_test.cc.s

aws/kinesis/core/test/shard_map_test.o: aws/kinesis/core/test/shard_map_test.cc.o

.PHONY : aws/kinesis/core/test/shard_map_test.o

# target to build an object file
aws/kinesis/core/test/shard_map_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/shard_map_test.cc.o
.PHONY : aws/kinesis/core/test/shard_map_test.cc.o

aws/kinesis/core/test/shard_map_test.i: aws/kinesis/core/test/shard_map_test.cc.i

.PHONY : aws/kinesis/core/test/shard_map_test.i

# target to preprocess a source file
aws/kinesis/core/test/shard_map_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/shard_map_test.cc.i
.PHONY : aws/kinesis/core/test/shard_map_test.cc.i

aws/kinesis/core/test/shard_map_test.s: aws/kinesis/core/test/shard_map_test.cc.s

.PHONY : aws/kinesis/core/test/shard_map_test.s

# target to generate assembly for a file
aws/kinesis/core/test/shard_map_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/shard_map_test.cc.s
.PHONY : aws/kinesis/core/test/shard_map_test.cc.s

aws/kinesis/core/test/test_utils.o: aws/kinesis/core/test/test_utils.cc.o

.PHONY : aws/kinesis/core/test/test_utils.o

# target to build an object file
aws/kinesis/core/test/test_utils.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/test_utils.cc.o
.PHONY : aws/kinesis/core/test/test_utils.cc.o

aws/kinesis/core/test/test_utils.i: aws/kinesis/core/test/test_utils.cc.i

.PHONY : aws/kinesis/core/test/test_utils.i

# target to preprocess a source file
aws/kinesis/core/test/test_utils.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/test_utils.cc.i
.PHONY : aws/kinesis/core/test/test_utils.cc.i

aws/kinesis/core/test/test_utils.s: aws/kinesis/core/test/test_utils.cc.s

.PHONY : aws/kinesis/core/test/test_utils.s

# target to generate assembly for a file
aws/kinesis/core/test/test_utils.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/test_utils.cc.s
.PHONY : aws/kinesis/core/test/test_utils.cc.s

aws/kinesis/core/test/user_record_test.o: aws/kinesis/core/test/user_record_test.cc.o

.PHONY : aws/kinesis/core/test/user_record_test.o

# target to build an object file
aws/kinesis/core/test/user_record_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/user_record_test.cc.o
.PHONY : aws/kinesis/core/test/user_record_test.cc.o

aws/kinesis/core/test/user_record_test.i: aws/kinesis/core/test/user_record_test.cc.i

.PHONY : aws/kinesis/core/test/user_record_test.i

# target to preprocess a source file
aws/kinesis/core/test/user_record_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/user_record_test.cc.i
.PHONY : aws/kinesis/core/test/user_record_test.cc.i

aws/kinesis/core/test/user_record_test.s: aws/kinesis/core/test/user_record_test.cc.s

.PHONY : aws/kinesis/core/test/user_record_test.s

# target to generate assembly for a file
aws/kinesis/core/test/user_record_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/test/user_record_test.cc.s
.PHONY : aws/kinesis/core/test/user_record_test.cc.s

aws/kinesis/core/user_record.o: aws/kinesis/core/user_record.cc.o

.PHONY : aws/kinesis/core/user_record.o

# target to build an object file
aws/kinesis/core/user_record.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/user_record.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/user_record.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/user_record.cc.o
.PHONY : aws/kinesis/core/user_record.cc.o

aws/kinesis/core/user_record.i: aws/kinesis/core/user_record.cc.i

.PHONY : aws/kinesis/core/user_record.i

# target to preprocess a source file
aws/kinesis/core/user_record.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/user_record.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/user_record.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/user_record.cc.i
.PHONY : aws/kinesis/core/user_record.cc.i

aws/kinesis/core/user_record.s: aws/kinesis/core/user_record.cc.s

.PHONY : aws/kinesis/core/user_record.s

# target to generate assembly for a file
aws/kinesis/core/user_record.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/core/user_record.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/core/user_record.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/core/user_record.cc.s
.PHONY : aws/kinesis/core/user_record.cc.s

aws/kinesis/main.o: aws/kinesis/main.cc.o

.PHONY : aws/kinesis/main.o

# target to build an object file
aws/kinesis/main.cc.o:
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/main.cc.o
.PHONY : aws/kinesis/main.cc.o

aws/kinesis/main.i: aws/kinesis/main.cc.i

.PHONY : aws/kinesis/main.i

# target to preprocess a source file
aws/kinesis/main.cc.i:
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/main.cc.i
.PHONY : aws/kinesis/main.cc.i

aws/kinesis/main.s: aws/kinesis/main.cc.s

.PHONY : aws/kinesis/main.s

# target to generate assembly for a file
aws/kinesis/main.cc.s:
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/main.cc.s
.PHONY : aws/kinesis/main.cc.s

aws/kinesis/protobuf/config.pb.o: aws/kinesis/protobuf/config.pb.cc.o

.PHONY : aws/kinesis/protobuf/config.pb.o

# target to build an object file
aws/kinesis/protobuf/config.pb.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/protobuf/config.pb.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/protobuf/config.pb.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/protobuf/config.pb.cc.o
.PHONY : aws/kinesis/protobuf/config.pb.cc.o

aws/kinesis/protobuf/config.pb.i: aws/kinesis/protobuf/config.pb.cc.i

.PHONY : aws/kinesis/protobuf/config.pb.i

# target to preprocess a source file
aws/kinesis/protobuf/config.pb.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/protobuf/config.pb.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/protobuf/config.pb.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/protobuf/config.pb.cc.i
.PHONY : aws/kinesis/protobuf/config.pb.cc.i

aws/kinesis/protobuf/config.pb.s: aws/kinesis/protobuf/config.pb.cc.s

.PHONY : aws/kinesis/protobuf/config.pb.s

# target to generate assembly for a file
aws/kinesis/protobuf/config.pb.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/protobuf/config.pb.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/protobuf/config.pb.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/protobuf/config.pb.cc.s
.PHONY : aws/kinesis/protobuf/config.pb.cc.s

aws/kinesis/protobuf/messages.pb.o: aws/kinesis/protobuf/messages.pb.cc.o

.PHONY : aws/kinesis/protobuf/messages.pb.o

# target to build an object file
aws/kinesis/protobuf/messages.pb.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/protobuf/messages.pb.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/protobuf/messages.pb.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/protobuf/messages.pb.cc.o
.PHONY : aws/kinesis/protobuf/messages.pb.cc.o

aws/kinesis/protobuf/messages.pb.i: aws/kinesis/protobuf/messages.pb.cc.i

.PHONY : aws/kinesis/protobuf/messages.pb.i

# target to preprocess a source file
aws/kinesis/protobuf/messages.pb.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/protobuf/messages.pb.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/protobuf/messages.pb.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/protobuf/messages.pb.cc.i
.PHONY : aws/kinesis/protobuf/messages.pb.cc.i

aws/kinesis/protobuf/messages.pb.s: aws/kinesis/protobuf/messages.pb.cc.s

.PHONY : aws/kinesis/protobuf/messages.pb.s

# target to generate assembly for a file
aws/kinesis/protobuf/messages.pb.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/protobuf/messages.pb.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/protobuf/messages.pb.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/kinesis/protobuf/messages.pb.cc.s
.PHONY : aws/kinesis/protobuf/messages.pb.cc.s

aws/kinesis/test/test.o: aws/kinesis/test/test.cc.o

.PHONY : aws/kinesis/test/test.o

# target to build an object file
aws/kinesis/test/test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/test/test.cc.o
.PHONY : aws/kinesis/test/test.cc.o

aws/kinesis/test/test.i: aws/kinesis/test/test.cc.i

.PHONY : aws/kinesis/test/test.i

# target to preprocess a source file
aws/kinesis/test/test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/test/test.cc.i
.PHONY : aws/kinesis/test/test.cc.i

aws/kinesis/test/test.s: aws/kinesis/test/test.cc.s

.PHONY : aws/kinesis/test/test.s

# target to generate assembly for a file
aws/kinesis/test/test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/kinesis/test/test.cc.s
.PHONY : aws/kinesis/test/test.cc.s

aws/kinesis/test_driver.o: aws/kinesis/test_driver.cc.o

.PHONY : aws/kinesis/test_driver.o

# target to build an object file
aws/kinesis/test_driver.cc.o:
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/test_driver.cc.o
.PHONY : aws/kinesis/test_driver.cc.o

aws/kinesis/test_driver.i: aws/kinesis/test_driver.cc.i

.PHONY : aws/kinesis/test_driver.i

# target to preprocess a source file
aws/kinesis/test_driver.cc.i:
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/test_driver.cc.i
.PHONY : aws/kinesis/test_driver.cc.i

aws/kinesis/test_driver.s: aws/kinesis/test_driver.cc.s

.PHONY : aws/kinesis/test_driver.s

# target to generate assembly for a file
aws/kinesis/test_driver.cc.s:
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/kinesis/test_driver.cc.s
.PHONY : aws/kinesis/test_driver.cc.s

aws/metrics/metrics_constants.o: aws/metrics/metrics_constants.cc.o

.PHONY : aws/metrics/metrics_constants.o

# target to build an object file
aws/metrics/metrics_constants.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_constants.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_constants.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_constants.cc.o
.PHONY : aws/metrics/metrics_constants.cc.o

aws/metrics/metrics_constants.i: aws/metrics/metrics_constants.cc.i

.PHONY : aws/metrics/metrics_constants.i

# target to preprocess a source file
aws/metrics/metrics_constants.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_constants.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_constants.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_constants.cc.i
.PHONY : aws/metrics/metrics_constants.cc.i

aws/metrics/metrics_constants.s: aws/metrics/metrics_constants.cc.s

.PHONY : aws/metrics/metrics_constants.s

# target to generate assembly for a file
aws/metrics/metrics_constants.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_constants.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_constants.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_constants.cc.s
.PHONY : aws/metrics/metrics_constants.cc.s

aws/metrics/metrics_index.o: aws/metrics/metrics_index.cc.o

.PHONY : aws/metrics/metrics_index.o

# target to build an object file
aws/metrics/metrics_index.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_index.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_index.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_index.cc.o
.PHONY : aws/metrics/metrics_index.cc.o

aws/metrics/metrics_index.i: aws/metrics/metrics_index.cc.i

.PHONY : aws/metrics/metrics_index.i

# target to preprocess a source file
aws/metrics/metrics_index.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_index.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_index.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_index.cc.i
.PHONY : aws/metrics/metrics_index.cc.i

aws/metrics/metrics_index.s: aws/metrics/metrics_index.cc.s

.PHONY : aws/metrics/metrics_index.s

# target to generate assembly for a file
aws/metrics/metrics_index.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_index.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_index.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_index.cc.s
.PHONY : aws/metrics/metrics_index.cc.s

aws/metrics/metrics_manager.o: aws/metrics/metrics_manager.cc.o

.PHONY : aws/metrics/metrics_manager.o

# target to build an object file
aws/metrics/metrics_manager.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_manager.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_manager.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_manager.cc.o
.PHONY : aws/metrics/metrics_manager.cc.o

aws/metrics/metrics_manager.i: aws/metrics/metrics_manager.cc.i

.PHONY : aws/metrics/metrics_manager.i

# target to preprocess a source file
aws/metrics/metrics_manager.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_manager.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_manager.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_manager.cc.i
.PHONY : aws/metrics/metrics_manager.cc.i

aws/metrics/metrics_manager.s: aws/metrics/metrics_manager.cc.s

.PHONY : aws/metrics/metrics_manager.s

# target to generate assembly for a file
aws/metrics/metrics_manager.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/metrics_manager.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/metrics/metrics_manager.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/metrics/metrics_manager.cc.s
.PHONY : aws/metrics/metrics_manager.cc.s

aws/metrics/test/accumulator_test.o: aws/metrics/test/accumulator_test.cc.o

.PHONY : aws/metrics/test/accumulator_test.o

# target to build an object file
aws/metrics/test/accumulator_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/accumulator_test.cc.o
.PHONY : aws/metrics/test/accumulator_test.cc.o

aws/metrics/test/accumulator_test.i: aws/metrics/test/accumulator_test.cc.i

.PHONY : aws/metrics/test/accumulator_test.i

# target to preprocess a source file
aws/metrics/test/accumulator_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/accumulator_test.cc.i
.PHONY : aws/metrics/test/accumulator_test.cc.i

aws/metrics/test/accumulator_test.s: aws/metrics/test/accumulator_test.cc.s

.PHONY : aws/metrics/test/accumulator_test.s

# target to generate assembly for a file
aws/metrics/test/accumulator_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/accumulator_test.cc.s
.PHONY : aws/metrics/test/accumulator_test.cc.s

aws/metrics/test/metric_test.o: aws/metrics/test/metric_test.cc.o

.PHONY : aws/metrics/test/metric_test.o

# target to build an object file
aws/metrics/test/metric_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/metric_test.cc.o
.PHONY : aws/metrics/test/metric_test.cc.o

aws/metrics/test/metric_test.i: aws/metrics/test/metric_test.cc.i

.PHONY : aws/metrics/test/metric_test.i

# target to preprocess a source file
aws/metrics/test/metric_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/metric_test.cc.i
.PHONY : aws/metrics/test/metric_test.cc.i

aws/metrics/test/metric_test.s: aws/metrics/test/metric_test.cc.s

.PHONY : aws/metrics/test/metric_test.s

# target to generate assembly for a file
aws/metrics/test/metric_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/metric_test.cc.s
.PHONY : aws/metrics/test/metric_test.cc.s

aws/metrics/test/metrics_manager_test.o: aws/metrics/test/metrics_manager_test.cc.o

.PHONY : aws/metrics/test/metrics_manager_test.o

# target to build an object file
aws/metrics/test/metrics_manager_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/metrics_manager_test.cc.o
.PHONY : aws/metrics/test/metrics_manager_test.cc.o

aws/metrics/test/metrics_manager_test.i: aws/metrics/test/metrics_manager_test.cc.i

.PHONY : aws/metrics/test/metrics_manager_test.i

# target to preprocess a source file
aws/metrics/test/metrics_manager_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/metrics_manager_test.cc.i
.PHONY : aws/metrics/test/metrics_manager_test.cc.i

aws/metrics/test/metrics_manager_test.s: aws/metrics/test/metrics_manager_test.cc.s

.PHONY : aws/metrics/test/metrics_manager_test.s

# target to generate assembly for a file
aws/metrics/test/metrics_manager_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/metrics/test/metrics_manager_test.cc.s
.PHONY : aws/metrics/test/metrics_manager_test.cc.s

aws/utils/backtrace/bsd_backtrace.o: aws/utils/backtrace/bsd_backtrace.cc.o

.PHONY : aws/utils/backtrace/bsd_backtrace.o

# target to build an object file
aws/utils/backtrace/bsd_backtrace.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/bsd_backtrace.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/bsd_backtrace.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/bsd_backtrace.cc.o
.PHONY : aws/utils/backtrace/bsd_backtrace.cc.o

aws/utils/backtrace/bsd_backtrace.i: aws/utils/backtrace/bsd_backtrace.cc.i

.PHONY : aws/utils/backtrace/bsd_backtrace.i

# target to preprocess a source file
aws/utils/backtrace/bsd_backtrace.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/bsd_backtrace.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/bsd_backtrace.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/bsd_backtrace.cc.i
.PHONY : aws/utils/backtrace/bsd_backtrace.cc.i

aws/utils/backtrace/bsd_backtrace.s: aws/utils/backtrace/bsd_backtrace.cc.s

.PHONY : aws/utils/backtrace/bsd_backtrace.s

# target to generate assembly for a file
aws/utils/backtrace/bsd_backtrace.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/bsd_backtrace.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/bsd_backtrace.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/bsd_backtrace.cc.s
.PHONY : aws/utils/backtrace/bsd_backtrace.cc.s

aws/utils/backtrace/gcc_backtrace.o: aws/utils/backtrace/gcc_backtrace.cc.o

.PHONY : aws/utils/backtrace/gcc_backtrace.o

# target to build an object file
aws/utils/backtrace/gcc_backtrace.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/gcc_backtrace.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/gcc_backtrace.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/gcc_backtrace.cc.o
.PHONY : aws/utils/backtrace/gcc_backtrace.cc.o

aws/utils/backtrace/gcc_backtrace.i: aws/utils/backtrace/gcc_backtrace.cc.i

.PHONY : aws/utils/backtrace/gcc_backtrace.i

# target to preprocess a source file
aws/utils/backtrace/gcc_backtrace.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/gcc_backtrace.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/gcc_backtrace.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/gcc_backtrace.cc.i
.PHONY : aws/utils/backtrace/gcc_backtrace.cc.i

aws/utils/backtrace/gcc_backtrace.s: aws/utils/backtrace/gcc_backtrace.cc.s

.PHONY : aws/utils/backtrace/gcc_backtrace.s

# target to generate assembly for a file
aws/utils/backtrace/gcc_backtrace.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/gcc_backtrace.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/gcc_backtrace.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/gcc_backtrace.cc.s
.PHONY : aws/utils/backtrace/gcc_backtrace.cc.s

aws/utils/backtrace/null_backtrace.o: aws/utils/backtrace/null_backtrace.cc.o

.PHONY : aws/utils/backtrace/null_backtrace.o

# target to build an object file
aws/utils/backtrace/null_backtrace.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/null_backtrace.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/null_backtrace.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/null_backtrace.cc.o
.PHONY : aws/utils/backtrace/null_backtrace.cc.o

aws/utils/backtrace/null_backtrace.i: aws/utils/backtrace/null_backtrace.cc.i

.PHONY : aws/utils/backtrace/null_backtrace.i

# target to preprocess a source file
aws/utils/backtrace/null_backtrace.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/null_backtrace.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/null_backtrace.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/null_backtrace.cc.i
.PHONY : aws/utils/backtrace/null_backtrace.cc.i

aws/utils/backtrace/null_backtrace.s: aws/utils/backtrace/null_backtrace.cc.s

.PHONY : aws/utils/backtrace/null_backtrace.s

# target to generate assembly for a file
aws/utils/backtrace/null_backtrace.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/backtrace/null_backtrace.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/backtrace/null_backtrace.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/backtrace/null_backtrace.cc.s
.PHONY : aws/utils/backtrace/null_backtrace.cc.s

aws/utils/logging.o: aws/utils/logging.cc.o

.PHONY : aws/utils/logging.o

# target to build an object file
aws/utils/logging.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/logging.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/logging.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/logging.cc.o
.PHONY : aws/utils/logging.cc.o

aws/utils/logging.i: aws/utils/logging.cc.i

.PHONY : aws/utils/logging.i

# target to preprocess a source file
aws/utils/logging.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/logging.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/logging.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/logging.cc.i
.PHONY : aws/utils/logging.cc.i

aws/utils/logging.s: aws/utils/logging.cc.s

.PHONY : aws/utils/logging.s

# target to generate assembly for a file
aws/utils/logging.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/logging.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/logging.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/logging.cc.s
.PHONY : aws/utils/logging.cc.s

aws/utils/processing_statistics_logger.o: aws/utils/processing_statistics_logger.cc.o

.PHONY : aws/utils/processing_statistics_logger.o

# target to build an object file
aws/utils/processing_statistics_logger.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/processing_statistics_logger.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/processing_statistics_logger.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/processing_statistics_logger.cc.o
.PHONY : aws/utils/processing_statistics_logger.cc.o

aws/utils/processing_statistics_logger.i: aws/utils/processing_statistics_logger.cc.i

.PHONY : aws/utils/processing_statistics_logger.i

# target to preprocess a source file
aws/utils/processing_statistics_logger.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/processing_statistics_logger.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/processing_statistics_logger.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/processing_statistics_logger.cc.i
.PHONY : aws/utils/processing_statistics_logger.cc.i

aws/utils/processing_statistics_logger.s: aws/utils/processing_statistics_logger.cc.s

.PHONY : aws/utils/processing_statistics_logger.s

# target to generate assembly for a file
aws/utils/processing_statistics_logger.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/processing_statistics_logger.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/processing_statistics_logger.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/processing_statistics_logger.cc.s
.PHONY : aws/utils/processing_statistics_logger.cc.s

aws/utils/segfault_signal.o: aws/utils/segfault_signal.cc.o

.PHONY : aws/utils/segfault_signal.o

# target to build an object file
aws/utils/segfault_signal.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/segfault_signal.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/segfault_signal.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/segfault_signal.cc.o
.PHONY : aws/utils/segfault_signal.cc.o

aws/utils/segfault_signal.i: aws/utils/segfault_signal.cc.i

.PHONY : aws/utils/segfault_signal.i

# target to preprocess a source file
aws/utils/segfault_signal.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/segfault_signal.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/segfault_signal.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/segfault_signal.cc.i
.PHONY : aws/utils/segfault_signal.cc.i

aws/utils/segfault_signal.s: aws/utils/segfault_signal.cc.s

.PHONY : aws/utils/segfault_signal.s

# target to generate assembly for a file
aws/utils/segfault_signal.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/segfault_signal.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/segfault_signal.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/segfault_signal.cc.s
.PHONY : aws/utils/segfault_signal.cc.s

aws/utils/signal_handler.o: aws/utils/signal_handler.cc.o

.PHONY : aws/utils/signal_handler.o

# target to build an object file
aws/utils/signal_handler.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/signal_handler.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/signal_handler.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/signal_handler.cc.o
.PHONY : aws/utils/signal_handler.cc.o

aws/utils/signal_handler.i: aws/utils/signal_handler.cc.i

.PHONY : aws/utils/signal_handler.i

# target to preprocess a source file
aws/utils/signal_handler.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/signal_handler.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/signal_handler.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/signal_handler.cc.i
.PHONY : aws/utils/signal_handler.cc.i

aws/utils/signal_handler.s: aws/utils/signal_handler.cc.s

.PHONY : aws/utils/signal_handler.s

# target to generate assembly for a file
aws/utils/signal_handler.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/signal_handler.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/signal_handler.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/signal_handler.cc.s
.PHONY : aws/utils/signal_handler.cc.s

aws/utils/spin_lock.o: aws/utils/spin_lock.cc.o

.PHONY : aws/utils/spin_lock.o

# target to build an object file
aws/utils/spin_lock.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/spin_lock.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/spin_lock.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/spin_lock.cc.o
.PHONY : aws/utils/spin_lock.cc.o

aws/utils/spin_lock.i: aws/utils/spin_lock.cc.i

.PHONY : aws/utils/spin_lock.i

# target to preprocess a source file
aws/utils/spin_lock.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/spin_lock.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/spin_lock.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/spin_lock.cc.i
.PHONY : aws/utils/spin_lock.cc.i

aws/utils/spin_lock.s: aws/utils/spin_lock.cc.s

.PHONY : aws/utils/spin_lock.s

# target to generate assembly for a file
aws/utils/spin_lock.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/spin_lock.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/spin_lock.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/spin_lock.cc.s
.PHONY : aws/utils/spin_lock.cc.s

aws/utils/test/concurrent_hash_map_test.o: aws/utils/test/concurrent_hash_map_test.cc.o

.PHONY : aws/utils/test/concurrent_hash_map_test.o

# target to build an object file
aws/utils/test/concurrent_hash_map_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/concurrent_hash_map_test.cc.o
.PHONY : aws/utils/test/concurrent_hash_map_test.cc.o

aws/utils/test/concurrent_hash_map_test.i: aws/utils/test/concurrent_hash_map_test.cc.i

.PHONY : aws/utils/test/concurrent_hash_map_test.i

# target to preprocess a source file
aws/utils/test/concurrent_hash_map_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/concurrent_hash_map_test.cc.i
.PHONY : aws/utils/test/concurrent_hash_map_test.cc.i

aws/utils/test/concurrent_hash_map_test.s: aws/utils/test/concurrent_hash_map_test.cc.s

.PHONY : aws/utils/test/concurrent_hash_map_test.s

# target to generate assembly for a file
aws/utils/test/concurrent_hash_map_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/concurrent_hash_map_test.cc.s
.PHONY : aws/utils/test/concurrent_hash_map_test.cc.s

aws/utils/test/concurrent_linked_queue_test.o: aws/utils/test/concurrent_linked_queue_test.cc.o

.PHONY : aws/utils/test/concurrent_linked_queue_test.o

# target to build an object file
aws/utils/test/concurrent_linked_queue_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/concurrent_linked_queue_test.cc.o
.PHONY : aws/utils/test/concurrent_linked_queue_test.cc.o

aws/utils/test/concurrent_linked_queue_test.i: aws/utils/test/concurrent_linked_queue_test.cc.i

.PHONY : aws/utils/test/concurrent_linked_queue_test.i

# target to preprocess a source file
aws/utils/test/concurrent_linked_queue_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/concurrent_linked_queue_test.cc.i
.PHONY : aws/utils/test/concurrent_linked_queue_test.cc.i

aws/utils/test/concurrent_linked_queue_test.s: aws/utils/test/concurrent_linked_queue_test.cc.s

.PHONY : aws/utils/test/concurrent_linked_queue_test.s

# target to generate assembly for a file
aws/utils/test/concurrent_linked_queue_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/concurrent_linked_queue_test.cc.s
.PHONY : aws/utils/test/concurrent_linked_queue_test.cc.s

aws/utils/test/spin_lock_test.o: aws/utils/test/spin_lock_test.cc.o

.PHONY : aws/utils/test/spin_lock_test.o

# target to build an object file
aws/utils/test/spin_lock_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/spin_lock_test.cc.o
.PHONY : aws/utils/test/spin_lock_test.cc.o

aws/utils/test/spin_lock_test.i: aws/utils/test/spin_lock_test.cc.i

.PHONY : aws/utils/test/spin_lock_test.i

# target to preprocess a source file
aws/utils/test/spin_lock_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/spin_lock_test.cc.i
.PHONY : aws/utils/test/spin_lock_test.cc.i

aws/utils/test/spin_lock_test.s: aws/utils/test/spin_lock_test.cc.s

.PHONY : aws/utils/test/spin_lock_test.s

# target to generate assembly for a file
aws/utils/test/spin_lock_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/spin_lock_test.cc.s
.PHONY : aws/utils/test/spin_lock_test.cc.s

aws/utils/test/token_bucket_test.o: aws/utils/test/token_bucket_test.cc.o

.PHONY : aws/utils/test/token_bucket_test.o

# target to build an object file
aws/utils/test/token_bucket_test.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/token_bucket_test.cc.o
.PHONY : aws/utils/test/token_bucket_test.cc.o

aws/utils/test/token_bucket_test.i: aws/utils/test/token_bucket_test.cc.i

.PHONY : aws/utils/test/token_bucket_test.i

# target to preprocess a source file
aws/utils/test/token_bucket_test.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/token_bucket_test.cc.i
.PHONY : aws/utils/test/token_bucket_test.cc.i

aws/utils/test/token_bucket_test.s: aws/utils/test/token_bucket_test.cc.s

.PHONY : aws/utils/test/token_bucket_test.s

# target to generate assembly for a file
aws/utils/test/token_bucket_test.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/test/token_bucket_test.cc.s
.PHONY : aws/utils/test/token_bucket_test.cc.s

aws/utils/utils.o: aws/utils/utils.cc.o

.PHONY : aws/utils/utils.o

# target to build an object file
aws/utils/utils.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/utils.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/utils.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/utils.cc.o
.PHONY : aws/utils/utils.cc.o

aws/utils/utils.i: aws/utils/utils.cc.i

.PHONY : aws/utils/utils.i

# target to preprocess a source file
aws/utils/utils.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/utils.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/utils.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/utils.cc.i
.PHONY : aws/utils/utils.cc.i

aws/utils/utils.s: aws/utils/utils.cc.s

.PHONY : aws/utils/utils.s

# target to generate assembly for a file
aws/utils/utils.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/utils.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/utils.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/utils.cc.s
.PHONY : aws/utils/utils.cc.s

aws/utils/writer_methods.o: aws/utils/writer_methods.cc.o

.PHONY : aws/utils/writer_methods.o

# target to build an object file
aws/utils/writer_methods.cc.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/writer_methods.cc.o
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/writer_methods.cc.o
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/writer_methods.cc.o
.PHONY : aws/utils/writer_methods.cc.o

aws/utils/writer_methods.i: aws/utils/writer_methods.cc.i

.PHONY : aws/utils/writer_methods.i

# target to preprocess a source file
aws/utils/writer_methods.cc.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/writer_methods.cc.i
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/writer_methods.cc.i
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/writer_methods.cc.i
.PHONY : aws/utils/writer_methods.cc.i

aws/utils/writer_methods.s: aws/utils/writer_methods.cc.s

.PHONY : aws/utils/writer_methods.s

# target to generate assembly for a file
aws/utils/writer_methods.cc.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/aws/utils/writer_methods.cc.s
	$(MAKE) -f CMakeFiles/test_driver.dir/build.make CMakeFiles/test_driver.dir/aws/utils/writer_methods.cc.s
	$(MAKE) -f CMakeFiles/kinesis_producer.dir/build.make CMakeFiles/kinesis_producer.dir/aws/utils/writer_methods.cc.s
.PHONY : aws/utils/writer_methods.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tests"
	@echo "... test_driver"
	@echo "... kinesis_producer"
	@echo "... aws/auth/mutable_static_creds_provider.o"
	@echo "... aws/auth/mutable_static_creds_provider.i"
	@echo "... aws/auth/mutable_static_creds_provider.s"
	@echo "... aws/auth/test/mutable_static_creds_provider_test.o"
	@echo "... aws/auth/test/mutable_static_creds_provider_test.i"
	@echo "... aws/auth/test/mutable_static_creds_provider_test.s"
	@echo "... aws/kinesis/core/ipc_manager.o"
	@echo "... aws/kinesis/core/ipc_manager.i"
	@echo "... aws/kinesis/core/ipc_manager.s"
	@echo "... aws/kinesis/core/kinesis_producer.o"
	@echo "... aws/kinesis/core/kinesis_producer.i"
	@echo "... aws/kinesis/core/kinesis_producer.s"
	@echo "... aws/kinesis/core/kinesis_record.o"
	@echo "... aws/kinesis/core/kinesis_record.i"
	@echo "... aws/kinesis/core/kinesis_record.s"
	@echo "... aws/kinesis/core/retrier.o"
	@echo "... aws/kinesis/core/retrier.i"
	@echo "... aws/kinesis/core/retrier.s"
	@echo "... aws/kinesis/core/shard_map.o"
	@echo "... aws/kinesis/core/shard_map.i"
	@echo "... aws/kinesis/core/shard_map.s"
	@echo "... aws/kinesis/core/test/aggregator_test.o"
	@echo "... aws/kinesis/core/test/aggregator_test.i"
	@echo "... aws/kinesis/core/test/aggregator_test.s"
	@echo "... aws/kinesis/core/test/ipc_manager_test.o"
	@echo "... aws/kinesis/core/test/ipc_manager_test.i"
	@echo "... aws/kinesis/core/test/ipc_manager_test.s"
	@echo "... aws/kinesis/core/test/kinesis_record_test.o"
	@echo "... aws/kinesis/core/test/kinesis_record_test.i"
	@echo "... aws/kinesis/core/test/kinesis_record_test.s"
	@echo "... aws/kinesis/core/test/limiter_test.o"
	@echo "... aws/kinesis/core/test/limiter_test.i"
	@echo "... aws/kinesis/core/test/limiter_test.s"
	@echo "... aws/kinesis/core/test/put_records_request_test.o"
	@echo "... aws/kinesis/core/test/put_records_request_test.i"
	@echo "... aws/kinesis/core/test/put_records_request_test.s"
	@echo "... aws/kinesis/core/test/reducer_test.o"
	@echo "... aws/kinesis/core/test/reducer_test.i"
	@echo "... aws/kinesis/core/test/reducer_test.s"
	@echo "... aws/kinesis/core/test/retrier_test.o"
	@echo "... aws/kinesis/core/test/retrier_test.i"
	@echo "... aws/kinesis/core/test/retrier_test.s"
	@echo "... aws/kinesis/core/test/shard_map_test.o"
	@echo "... aws/kinesis/core/test/shard_map_test.i"
	@echo "... aws/kinesis/core/test/shard_map_test.s"
	@echo "... aws/kinesis/core/test/test_utils.o"
	@echo "... aws/kinesis/core/test/test_utils.i"
	@echo "... aws/kinesis/core/test/test_utils.s"
	@echo "... aws/kinesis/core/test/user_record_test.o"
	@echo "... aws/kinesis/core/test/user_record_test.i"
	@echo "... aws/kinesis/core/test/user_record_test.s"
	@echo "... aws/kinesis/core/user_record.o"
	@echo "... aws/kinesis/core/user_record.i"
	@echo "... aws/kinesis/core/user_record.s"
	@echo "... aws/kinesis/main.o"
	@echo "... aws/kinesis/main.i"
	@echo "... aws/kinesis/main.s"
	@echo "... aws/kinesis/protobuf/config.pb.o"
	@echo "... aws/kinesis/protobuf/config.pb.i"
	@echo "... aws/kinesis/protobuf/config.pb.s"
	@echo "... aws/kinesis/protobuf/messages.pb.o"
	@echo "... aws/kinesis/protobuf/messages.pb.i"
	@echo "... aws/kinesis/protobuf/messages.pb.s"
	@echo "... aws/kinesis/test/test.o"
	@echo "... aws/kinesis/test/test.i"
	@echo "... aws/kinesis/test/test.s"
	@echo "... aws/kinesis/test_driver.o"
	@echo "... aws/kinesis/test_driver.i"
	@echo "... aws/kinesis/test_driver.s"
	@echo "... aws/metrics/metrics_constants.o"
	@echo "... aws/metrics/metrics_constants.i"
	@echo "... aws/metrics/metrics_constants.s"
	@echo "... aws/metrics/metrics_index.o"
	@echo "... aws/metrics/metrics_index.i"
	@echo "... aws/metrics/metrics_index.s"
	@echo "... aws/metrics/metrics_manager.o"
	@echo "... aws/metrics/metrics_manager.i"
	@echo "... aws/metrics/metrics_manager.s"
	@echo "... aws/metrics/test/accumulator_test.o"
	@echo "... aws/metrics/test/accumulator_test.i"
	@echo "... aws/metrics/test/accumulator_test.s"
	@echo "... aws/metrics/test/metric_test.o"
	@echo "... aws/metrics/test/metric_test.i"
	@echo "... aws/metrics/test/metric_test.s"
	@echo "... aws/metrics/test/metrics_manager_test.o"
	@echo "... aws/metrics/test/metrics_manager_test.i"
	@echo "... aws/metrics/test/metrics_manager_test.s"
	@echo "... aws/utils/backtrace/bsd_backtrace.o"
	@echo "... aws/utils/backtrace/bsd_backtrace.i"
	@echo "... aws/utils/backtrace/bsd_backtrace.s"
	@echo "... aws/utils/backtrace/gcc_backtrace.o"
	@echo "... aws/utils/backtrace/gcc_backtrace.i"
	@echo "... aws/utils/backtrace/gcc_backtrace.s"
	@echo "... aws/utils/backtrace/null_backtrace.o"
	@echo "... aws/utils/backtrace/null_backtrace.i"
	@echo "... aws/utils/backtrace/null_backtrace.s"
	@echo "... aws/utils/logging.o"
	@echo "... aws/utils/logging.i"
	@echo "... aws/utils/logging.s"
	@echo "... aws/utils/processing_statistics_logger.o"
	@echo "... aws/utils/processing_statistics_logger.i"
	@echo "... aws/utils/processing_statistics_logger.s"
	@echo "... aws/utils/segfault_signal.o"
	@echo "... aws/utils/segfault_signal.i"
	@echo "... aws/utils/segfault_signal.s"
	@echo "... aws/utils/signal_handler.o"
	@echo "... aws/utils/signal_handler.i"
	@echo "... aws/utils/signal_handler.s"
	@echo "... aws/utils/spin_lock.o"
	@echo "... aws/utils/spin_lock.i"
	@echo "... aws/utils/spin_lock.s"
	@echo "... aws/utils/test/concurrent_hash_map_test.o"
	@echo "... aws/utils/test/concurrent_hash_map_test.i"
	@echo "... aws/utils/test/concurrent_hash_map_test.s"
	@echo "... aws/utils/test/concurrent_linked_queue_test.o"
	@echo "... aws/utils/test/concurrent_linked_queue_test.i"
	@echo "... aws/utils/test/concurrent_linked_queue_test.s"
	@echo "... aws/utils/test/spin_lock_test.o"
	@echo "... aws/utils/test/spin_lock_test.i"
	@echo "... aws/utils/test/spin_lock_test.s"
	@echo "... aws/utils/test/token_bucket_test.o"
	@echo "... aws/utils/test/token_bucket_test.i"
	@echo "... aws/utils/test/token_bucket_test.s"
	@echo "... aws/utils/utils.o"
	@echo "... aws/utils/utils.i"
	@echo "... aws/utils/utils.s"
	@echo "... aws/utils/writer_methods.o"
	@echo "... aws/utils/writer_methods.i"
	@echo "... aws/utils/writer_methods.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

