set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELEASE} /MT")

set(PLATFORM_SPECIFIC_SOURCE aws/utils/wincrypt_md5_hasher.cc)

add_definitions("-DDLL_EXPORT=__declspec(dllexport)")
add_definitions("-D_WIN32_WINNT=0x0601")

include("cmake/third-party.cmake")

if (MSVC)
	file(GLOB ROOT_HEADERS "aws/*.h")
	source_group("Header Files\\aws" FILES ${ROOT_HEADERS})
	file(GLOB AUTH_HEADERS "aws/auth/*.h")
	source_group("Header Files\\aws\\auth" FILES ${AUTH_HEADERS})
	file(GLOB_RECURSE CORE_HEADERS "aws/kinesis/core/*.h")
	source_group("Header Files\\aws\\kinesis\\core" FILES ${CORE_HEADERS})
	file(GLOB METRICS_HEADERS "aws/metrics/*.h")
	source_group("Header Files\\aws\\metrics" FILES ${METRICS_HEADERS})
	file(GLOB_RECURSE UTIL_HEADERS "aws/utils/*.h")
	source_group("Header Files\\aws\\utils" FILES ${UTIL_HEADERS})

	file(GLOB CORE_SOURCE "aws/kinesis/core/*.c*")
	source_group("Source Files\\aws\\core" FILES ${CORE_SOURCE})
	file(GLOB METRICS_SOURCE "aws/metrics/*.c*")
	source_group("Source Files\\aws\\metrics" FILES ${METRICS_SOURCE})
	file(GLOB UTIL_SOURCE "aws/utils/*.c*")
	source_group("Source Files\\aws\\utils" FILES ${UTIL_SOURCE})
	file(GLOB BACKTRACE_SOURCE "aws/utils/backtrace/*.c*")
	source_group("Source Files\\aws\\utils\\backtrace" FILES ${BACKTRACE_SOURCE})

	file(GLOB TEST_CORE_SOURCE "aws/kinesis/core/test/*.c*")
	source_group("Test Source Files\\aws\\core" FILES ${TEST_CORE_SOURCE})
	file(GLOB TEST_METRICS_SOURCE "aws/metrics/test/*.c*")
	source_group("Test Source Files\\aws\\metrics" FILES ${TEST_METRICS_SOURCE})
	file(GLOB TEST_UTIL_SOURCE "aws/utils/test/*.c*")
	source_group("Test Source Files\\aws\\utils" FILES ${TEST_UTIL_SOURCE})	

endif()