name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: bootstrap
      run: |
        chmod +x bootstrap.sh  # Ensure the script is executable
        ./bootstrap.sh
